# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    target-branch: "main"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - dependencies
    assignees:
      - pablopfg
    reviewers:
      - pablopfg
    ignore:
      - dependency-name: "@types/express"
        versions:
          - ">= 4.17.21"
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions:
          - ">= 6.21.0"
      - dependency-name: "@typescript-eslint/parser"
        versions:
          - ">= 6.21.0"
      - dependency-name: "eslint"
        versions:
          - ">= 8.57.1"